### ISSUE TITLE
Pitching Ideas

### ISSUE THREAD

**Issue by anisotropi4** [geocompr/py#51] opened 2022-05-29 18:29 UTC
Good evening,

Following a short exchange with Robin on Twitter I'd like see how I could contribute to the project. Which prompts the question, who is the target audience? and how can I help?

For my part I use Open Data sources to present interactive data visualization as hobby. Examples includes:
- Population and census data from the Office of National Statistics (ONS) and National Library of Scotland, 
- Transport network data from OpenStreetMap (OSM)  
- Transport locations from the National Passenger Transport Node (NaPTAN) 
- Planning and operation data from Network Rail OpenDataFeeds 

You appear to have covered these already but I typically use shell scripts and python on Linux to extract, clean and wrangle data using python with numpy, pandas, GeoPandas, Networkx, OSMnx and SciPy. I've also being playing with PySAL (Python Spacial Analytics Library) and sklearn (Scikit Learn).

For what it's worth, my day job is bit more prosaic, I am technical lead on projects involving national planning, operations and performance industry data exchange on the British network and have a role in European rail data exchange governance. 

Given all this, my initial thought would be to take one of the visualizations, say how to draw an interactive population map [here](https://anisotropi4.github.io/density/index.html) ![density](https://user-images.githubusercontent.com/27144121/170885914-d9f91938-a865-4ee9-947f-b2d34f283d30.png)

Or perhaps trunk road and rail transport map [here](https://anisotropi4.github.io/parallel/) or fizzy-knitting* map of the British Railway such as [here](https://electricrailmap.gitlab.io). 

Does any of this work? 

Apologies for the length of the note. Shout if you have any questions with this stuff.

Ta,

Will

**Comment by Robinlovelace** [comment] 2022-05-29 19:30
Hi Will, many thanks for chiming in! Just like Geocomputation with R, the plan for this project is for the community, meaning anyone who gets involved with ideas, to help direct the project. So your ideas here are v. welcome. 

In terms of target audience, the aim for this book is for it to be a stepping stone for people just getting started in the field. So instead of covering lots of ground quickly the plan is to start slow and to spend a lot of time/words explaining each concept, package and, ultimately, each line of code. This is the approach I think we have successfully used in Chapter 2: https://geocompr.github.io/py/02-spatial-data.html

Thoughts on how you could help:

- Reading existing content, reproducing results (and the book, all open source) and identifying gaps in the logic or ways we could do or word things better
- Proposing additional topics, which is exactly what you have done above. My first thought on that is that, as you say, the interactive mapping examples, could be of use. A simple demo of creating an attractive and scalable map (which your examples show well) could fit perfectly here, and I would say 'go for it' if you're happy to contribute: https://geocompr.github.io/py/09-mapping.html#interactive-maps

In terms of how to contribute, I imagine a PR that edits lines of code just below this could be a good place to start (we have discussed interactive mapping packages in #7 and #29 but happy to go with your suggestions here as you clearly have experience):

https://github.com/geocompr/py/blob/3a3a102fedb122c214a906ca64fd0b63852fbc07/09-mapping.qmd#L64-L69

**Comment by anisotropi4** [comment] 2022-05-29 21:12
Hi Robin, thanks for this. I'll sort out a pull request and look to update the interactive map piece. 

Looking at this my first thought is an interactive density map a bit like the one [here](http://bl.ocks.org/anisotropi4/5002794c84d7b2536ab08206aead8a6b). 

This is based on a tool-chain that:
1. Downloads the census OA geography and data, 
2. Builds mapbox "tippecanoe" from [here](https://github.com/mapbox/tippecanoe)  
3. Used "tippecanoe" to renders the data as vector-tiles
4. The interactive population density map is a web-based "leaflet.js" render        

My concern is that it might be a bit "heavy weight" for the book. There may be an another way to produce an interactive map or render this directly in python, but I don't know how. 

I'm also not familiar with Holoviews or Panel.

Loading this as a gist on GitHub, GitLab or a website then touches on "9.3.3. Publishing interactive maps" as this then just "works".

Any thoughts or comments welcome. Otherwise I'll have a look in the week and draft something then.

**Comment by Robinlovelace** [comment] 2022-05-30 08:27
I think it will be awesome. I've used tippecanoe and it's great. The key is explaining the concepts, vector tiles are important and including your proposed steps 1:4 will be a WIN for readers IMO. So main thoughts: go for it, and thank you!

**Comment by anisotropi4** [comment] 2022-05-30 22:49
A quick update as work rather got in the way today but I have started.

I'm going to propose a layered approach based on railway and public transport nodes. I say this as an interactive full population density visualization is perhaps not in the spirit of a gentle introduction. So my thoughts are that it is layered:

1. Render railway and metro stations, and ferry ports using the NaPTAN dataset using python, dump this to GeoJSON and render this as a simple leaflet.js interactive visualization. Potentially overlayed onto the standard OSM tiles to introduce the idea of tile-servers.
2. Use python and the OSMnx library to grab OSM railway track line-geometry. It is a bit slow as it is based on playing nice with OverPass, it might be worthwhile giving the code as an example and presenting the data as a "cooked" data-source. The interactive track would then be rendered using tippecanoe vector tiles and leaflet. This could then be used to explore, say, electrification following excellent work to try and fix the OSM data for this lead by Garry Keenor.  
3. Use python and tippecanoe to render an interactive GB Output Area population density based on the 2011 census

These then demonstrate simple point, line and area geometry interactive maps with a increased scale of complexity.   

Anyway, thanks to @Robinlovelace for the heads up about the protomaps fork. I hadn't spotted the MapBox deprecation and would be more than happy to used Brandon's fork for 2 & 3

**Comment by anisotropi4** [comment] 2022-05-30 22:54
As a final point, there are then a couple of extensions to this, however it's not clear to me whether this would fit within the scope of an introductory text. This is more where I've been looking at more recently which is why I mention it
1. Re-project the population density onto equal area squares, say 128x128 rather than the somewhat arcane OA geography using the tobler library as part of PySal. You could then use this, for example, to look at the FoI release of car ownership.
2. Look at an interactive vector tile map showing the nearest public transport node, that is rail, metro or ferry and/or to the nearest railway line. This could introduce the concept of stuff like projections to calculate distance*, finding the centroid of polygon features and looking at efficient shortest distance calculations.

* For example WSG84 to EPSG:32630

As above, I don't if this would be too much though

**Comment by Robinlovelace** [comment] 2022-05-31 06:47
Hi @anisotropi4 this all sounds good to me, a layered approach based on railway and public transport nodes would be great and aligns with our interest in transport and sustainability. The extension idea sounds good but let's get the MVP going first and see how it pans out. FYI we had a section on applications on the book that inspired this project (Geocomputation with R) that did get quite advanced. We also can have appendices to show advanced concepts/applications, which I'm 100% in favour of doing although not necessarily in the main book format which we plan to have printed as a physical book.

**Comment by anisotropi4** [comment] 2022-06-06 21:25
Good evening. A quick update, I now have scrubbed code for 1 and 2. I have found some bugs with 3 and will fix that and prepare a patch release

**Comment by Robinlovelace** [comment] 2022-06-06 21:47
Fantastic, many thanks. Looking forward to seeing this!

**Comment by Robinlovelace** [comment] 2022-06-25 13:27
Just a nudge on this @anisotropi4, do you want any input or code review from us? @anitagraser is probably the most experience Python developer here but I'm happy to take a look and give my (perhaps rather uninformed) opinion.

**Comment by anisotropi4** [comment] 2022-06-25 20:56
Good evening @Robinlovelace, yes please. I do need help as I don't know how to integrate two of the three toolchains into a book format nor how the narrative for the reader to follow. 

Where I have got to is code that:
1. Downloads NaPTAN and creates train stations and tram stops locatoins, dump this to GeoJSON and render this as a simple leaflet.js interactive visualization in JavaScript on standard OSM tiles to introduce the idea of tile-servers.
2. Downloads OSM rail and road network data and renders this as either an interactive GeoJSON file render, and as Tippecanoe vectortiles  

I appreciate the nudge as I also got distracted on the population density render, looking to replace JavaScript with Folium and prosaic things such as a job, a weeks' holiday in the Netherlands and ONS changes in the way they present population data and geography.My thought would be to create a scratch repository on GitHub and put this for your (@Robinlovelace @anitagraser) review. 

Please bear with me this weekend as as I only got home from Sloterdijk about two hours ago.

**Comment by anisotropi4** [comment] 2022-06-26 12:14
@Robinlovelace and @anitagraser I've created an initial NaPTAN push request based on the Chapter 9 code. I'll upload the associated data files and index.html now, and then create a second push request for the OSMnx data visualisation

**Comment by Robinlovelace** [comment] 2022-06-26 19:35
Overall, this looks like a really great example. I'm not a Python pro but from a look at the code it looks clean, well-documented and highly educational which is a key aim of this project. I think we should merge this for sure, notwithstanding my comment about large files in the commit history. Looking forward to hear what others thinks.

**Comment by Robinlovelace** [comment] 2022-06-28 10:08
Update on this @anisotropi4 now that #56 is fixed the CI should work properly.

**Comment by anisotropi4** [comment] 2022-06-28 18:33
I've looked at the other two examples (rail network and population density) and the data is large in comparison to the NaPTAN data example which puts me in a bit of a quandary. For example, OSMnx cache for the British Isles is about 200M and resulting GeoPackage fille is about 36MB and the Output Area geography is even bigger. I can look to prune the geography but still it is likely to be quite large which. Any thoughts on what to do?

**Comment by Robinlovelace** [comment] 2022-06-28 19:09
My suggestion: host the files somewhere, e.g. in the releases https://github.com/geocompr/py/releases/ page of this repo, but not in the commit history.

**Comment by anisotropi4** [comment] 2022-07-02 13:47
Two things, there is an update for the NaPTAN visualisation in the PR which hopefully better fulfills the brief (smaller data footprint, more pythonic) and if that is acceptable I'll get on with the other examples.

Then, I don't seem to have permission  to the releases directory and it's not clear how to access this to upload data as suggested above.

**Comment by Robinlovelace** [comment] 2022-07-02 17:18
Great, can you open a new PR that avoids the big data files (if you haven't already, apologies if I missed it). In the PR you sent I still see this: 

![image](https://user-images.githubusercontent.com/1825120/177010113-9b037225-a36d-41f6-a2b9-f042d30d4fe9.png)

Just tested cloning the repo and it provides more details on the size the repo would if we merge this:

```
gh repo clone anisotropi4/py
Cloning into 'py'...
remote: Enumerating objects: 3623, done.
remote: Counting objects: 100% (3623/3623), done.
remote: Compressing objects: 100% (1183/1183), done.
remote: Total 3623 (delta 2246), reused 3581 (delta 2228), pack-reused 0
Receiving objects: 100% (3623/3623), 20.86 MiB | 13.84 MiB/s, done.
Resolving deltas: 100% (2246/2246), done.
Updating upstream
From https://github.com/geocompr/py
 * [new branch]      main       -> upstream/main
```

**Comment by Robinlovelace** [comment] 2022-07-02 17:20
In fact, take that back, it seems your fork is only fractionally bigger:

```
gh repo clone geocompr/py
Cloning into 'py'...
remote: Enumerating objects: 3814, done.
remote: Counting objects: 100% (3814/3814), done.
remote: Compressing objects: 100% (1203/1203), done.
remote: Total 3814 (delta 2416), reused 3778 (delta 2390), pack-reused 0
Receiving objects: 100% (3814/3814), 21.53 MiB | 15.16 MiB/s, done.
Resolving deltas: 100% (2416/2416), done.
```

So I no longer see size as an issue, apologies. In general, I think you've responded to our various comments and big :+1: from me.

**Comment by Robinlovelace** [comment] 2022-09-28 13:57
Hi @anisotropi4 just reviewing where we're up to on the book and I think next step is to describe your code and integrate it, in some way, into the main text as per #74. Any of your initial ideas could go in as separate issues but, to keep the issue tracker tidy and to keep the momentum up closing for now.

**Closed by Robinlovelace** 2022-09-28 13:57 UTC
Labels: enhancement
